namePrefix: kustomize-

resources:
- deployment.yml
- ingress.yml
- services.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: lehtux/argocd
  newTag: d626f258cd4ce8dbdfa5a294b95353a564ef338b
